[redshift]
; Farbtemperatur: Tag / Nacht
temp-day=6500
temp-night=3500

; Helligkeit: Tag / Nacht
brightness-day=1.0
brightness-night=0.8

; Übergangsgeschwindigkeit
transition=1

; Standort (Deutschland, Mitte)
; Für automatische Erkennung: location-provider=geoclue2
[manual]
lat=51.5
lon=10.0
